org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.caching.debug=false
kotlin.code.style = official

# Project
mod.id = modernnetworking
mod.group = xyz.bluspring.modernnetworking
mod.version = 2.0.1
mod.name = ModernNetworking
mod.sources = https://github.com/BluSpring/ModernNetworking
mod.description = Multiversioned and multiloader network packet API based on 1.20.6+'s method of packets.

# Publishing
publishing.curseforge = 1251794
publishing.modrinth = yMou0v20
