name: ModernNetworking
main: xyz.bluspring.modernnetworking.bukkit.ModernNetworkingBukkit
version: ${version}
description: Multiversioned and multiloader network packet API based on 1.20.6+'s method of packets.
author: BluSpring
website: https://bluspring.xyz

# We support as far back as 1.16, and shouldn't need to really change this code much for newer versions,
# as we're not really messing with NMS. If any future versions break with this, then we should make a separate
# package for it.
api-version: '1.16'
folia-supported: true